### ISSUE TITLE
Make the code duplicate less

### ISSUE THREAD

**Issue by dracco1993** [RAR1741/RA18_RobotCode#41]
[Code duplication](https://codeclimate.com/github/RAR1741/RA18_RobotCode/issues?category%5B%5D=duplication&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=structure&engine_name%5B%5D=duplication&engine_name%5B%5D=checkstyle&engine_name%5B%5D=pmd&engine_name%5B%5D=sonar-java)

**Comment by randomtestfive** [comment]
haha all of the problems were in config
