### ISSUE TITLE
Use TalonSRX follow mode in drivetrain

### ISSUE THREAD

**Issue by randomtestfive** [RAR1741/RA18_RobotCode#73]
back motors (without encodes) should follow front motors (with encoders).

**Comment by themisfitfox** [comment]
I found the section in the documentation on how to do this. Starting branch add_drive_slave and implementing.

The documentation: [Here](http://www.roxbotix.org/TalonSRXManual.pdf) on page 39.

**Comment by randomtestfive** [comment]
heres real doc:
https://github.com/CrossTheRoadElec/Phoenix-Documentation/blob/master/README.md#follower

**Comment by randomtestfive** [comment]
closed by #75
